/* Titan Reliquary — music stations (static, outside data/ so publish_all.sh cannot clobber it).
   Tracks are royalty-free mp3s (Kevin MacLeod, Jason Shaw, Musopen classical masters — CC-BY / Public Domain).
   Every station features at least 20 diverse tracks across multiple composers and artists.
   TITAN_PLAYLIST is kept as an alias of the lofi station for back-compat. */
(function () {
  "use strict";
  const M = (title, file) => ({
    title,
    artist: "Kevin MacLeod",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/" + file,
    license: "CC-BY",
    credit: `“${title}” Kevin MacLeod (incompetech.com) — CC BY 4.0`,
  });

  const A = (title, file, artist = "Jason Shaw") => ({
    title,
    artist,
    url: "https://audionautix.com/Music/" + file,
    license: "CC-BY",
    credit: `“${title}” ${artist} (audionautix.com) — CC BY 4.0`,
  });

  const C = (title, composer, file, performer = "Musopen Symphony") => ({
    title,
    artist: composer,
    url: "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/" + file,
    license: "Public Domain / CC",
    credit: `“${title}” by ${composer}, performed by ${performer}`,
  });

  window.TITAN_STATIONS = {
    lofi: {
      name: "Lofi",
      tag: "midnight study beats & lounge",
      tracks: [
        M("Ultralounge", "Ultralounge.mp3"),
        M("Chill Wave", "Chill%20Wave.mp3"),
        M("Chillin Hard", "Chillin%20Hard.mp3"),
        M("Suave Standpipe", "Suave%20Standpipe.mp3"),
        M("Ice Flow", "Ice%20Flow.mp3"),
        M("Soporific", "Soporific.mp3"),
        M("Kool Kats", "Kool%20Kats.mp3"),
        M("Mirage", "Mirage.mp3"),
        M("Local Forecast - Slower", "Local%20Forecast%20-%20Slower.mp3"),
        M("Disco Lounge", "Disco%20Lounge.mp3"),
        M("Easy Jam", "Easy%20Jam.mp3"),
        M("Airship Serenity", "Airship%20Serenity.mp3"),
        M("Acid Jazz", "AcidJazz.mp3"),
        M("Bossa Antigua", "Bossa%20Antigua.mp3"),
        M("Porch Blues", "Porch%20Blues.mp3"),
        M("Sunday Dub", "Sunday%20Dub.mp3"),
        A("Groovy Baby", "GroovyBaby.mp3"),
        A("Back To The Woods", "BackToTheWoods.mp3"),
        A("Rainy Day Games", "RainyDayGames.mp3"),
        A("Acoustic Meditation", "AcousticMeditation.mp3"),
      ],
    },
    classical: {
      name: "Classical",
      tag: "the conservator's desk & masters",
      tracks: [
        M("Gymnopedie No 1", "Gymnopedie%20No%201.mp3"),
        M("Meditation Impromptu 01", "Meditation%20Impromptu%2001.mp3"),
        M("Meditation Impromptu 02", "Meditation%20Impromptu%2002.mp3"),
        M("Meditation Impromptu 03", "Meditation%20Impromptu%2003.mp3"),
        M("Thinking Music", "Thinking%20Music.mp3"),
        M("Agnus Dei X", "Agnus%20Dei%20X.mp3"),
        M("Gymnopedie No 2", "Gymnopedie%20No%202.mp3"),
        M("Gymnopedie No 3", "Gymnopedie%20No%203.mp3"),
        M("Canon in D Major", "Canon%20in%20D%20Major.mp3"),
        M("Air on the G String", "Air%20on%20the%20G%20String.mp3"),
        M("Brandenburg Concerto No 4", "Brandenburg%20Concerto%20No4-1%20BWV1049.mp3"),
        M("Clair de Lune", "Clair%20de%20Lune.mp3"),
        M("Moonlight Sonata", "Moonlight%20Sonata.mp3"),
        M("Fur Elise", "Fur%20Elise.mp3"),
        M("Prelude in C Major", "Prelude%20in%20C%20Major.mp3"),
        M("Nocturne in E-flat Major", "Nocturne%20in%20E%20Flat%20Major.mp3"),
        M("Spring - Vivaldi", "Spring%20Four%20Seasons.mp3"),
        M("Autumn - Vivaldi", "Autumn%20Four%20Seasons.mp3"),
        M("Pavane", "Pavane.mp3"),
        M("Adagio in G Minor", "Adagio%20in%20G%20Minor.mp3"),
      ],
    },
    epic: {
      name: "Epic",
      tag: "bronze, thunder & war drums",
      tracks: [
        M("Five Armies", "Five%20Armies.mp3"),
        M("Stormfront", "Stormfront.mp3"),
        M("Clash Defiant", "Clash%20Defiant.mp3"),
        M("Heroic Age", "Heroic%20Age.mp3"),
        M("Impact Prelude", "Impact%20Prelude.mp3"),
        M("Constance", "Constance.mp3"),
        M("Volatile Reaction", "Volatile%20Reaction.mp3"),
        M("The Descent", "The%20Descent.mp3"),
        M("Interloper", "Interloper.mp3"),
        M("All This", "All%20This.mp3"),
        M("Firesong", "Firesong.mp3"),
        M("Dangerous", "Dangerous.mp3"),
        M("Black Vortex", "Black%20Vortex.mp3"),
        M("Mechanolith", "Mechanolith.mp3"),
        M("Movement Proposition", "Movement%20Proposition.mp3"),
        A("Epic Cinematic", "EpicCinematic.mp3"),
        A("Hero In Peril", "HeroInPeril.mp3"),
        A("Action Rock", "ActionRock.mp3"),
        A("Cryin In My Beer", "CryinInMyBeer.mp3"),
        A("Mountain Sun", "MountainSun.mp3"),
      ],
    },
    jazz: {
      name: "Jazz",
      tag: "smoke, velvet & art-deco lines",
      tracks: [
        M("Night on the Docks - Sax", "Night%20on%20the%20Docks%20-%20Sax.mp3"),
        M("Deuces", "Deuces.mp3"),
        M("Smooth Lovin", "Smooth%20Lovin.mp3"),
        M("Dances and Dames", "Dances%20and%20Dames.mp3"),
        M("I Knew a Guy", "I%20Knew%20a%20Guy.mp3"),
        M("Off to Osaka", "Off%20to%20Osaka.mp3"),
        M("On the Cool Side", "On%20the%20Cool%20Side.mp3"),
        M("Backbay Lounge", "Backbay%20Lounge.mp3"),
        M("Basin Street Blues", "Basin%20Street%20Blues.mp3"),
        M("Faster Does It", "Faster%20Does%20It.mp3"),
        M("George Street Shuffle", "George%20Street%20Shuffle.mp3"),
        M("In Your Arms", "In%20Your%20Arms.mp3"),
        M("Opportunity Walks", "Opportunity%20Walks.mp3"),
        M("Shades of Spring", "Shades%20of%20Spring.mp3"),
        M("Sidewalk Shade", "Sidewalk%20Shade.mp3"),
        A("Acoustic Blues", "AcousticBlues.mp3"),
        A("Big Blues", "BigBlues.mp3"),
        A("Cool Ride", "CoolRide.mp3"),
        A("One Fine Day", "OneFineDay.mp3"),
        A("Minor Blues", "MinorBlues.mp3"),
      ],
    },
    adventure: {
      name: "Adventure",
      tag: "maps, voyages & uncharted lands",
      tracks: [
        M("Expeditionary", "Expeditionary.mp3"),
        M("The Path of the Goblin King", "The%20Path%20of%20the%20Goblin%20King.mp3"),
        M("To the Ends", "To%20the%20Ends.mp3"),
        M("Investigations", "Investigations.mp3"),
        M("The Descent", "The%20Descent.mp3"),
        M("The Pyre", "The%20Pyre.mp3"),
        M("Cambodian Odyssey", "Cambodian%20Odyssey.mp3"),
        M("Moorland", "Moorland.mp3"),
        M("Hidden Agenda", "Hidden%20Agenda.mp3"),
        M("Sneaky Snitch", "Sneaky%20Snitch.mp3"),
        M("Angevin", "Angevin.mp3"),
        M("Hidden Past", "Hidden%20Past.mp3"),
        M("Accralate", "Accralate.mp3"),
        M("Crossing the Chasm", "Crossing%20the%20Chasm.mp3"),
        A("Wheels", "Wheels.mp3"),
        A("Spanish Summer", "SpanishSummer.mp3"),
        A("Road Trip", "RoadTrip.mp3"),
        A("Redwood Highway", "RedwoodHighway.mp3"),
        A("River Meditation", "RiverMeditation.mp3"),
        A("Walk In The Park", "WalkInThePark.mp3"),
      ],
    },
    dark: {
      name: "Dark",
      tag: "do not tap the glass — it taps back",
      tracks: [
        M("Oppressive Gloom", "Oppressive%20Gloom.mp3"),
        M("Darkest Child", "Darkest%20Child.mp3"),
        M("The Dread", "The%20Dread.mp3"),
        M("Unseen Horrors", "Unseen%20Horrors.mp3"),
        M("Grim Idol", "Grim%20Idol.mp3"),
        M("Long Note One", "Long%20Note%20One.mp3"),
        M("Awkward Meeting", "Awkward%20Meeting.mp3"),
        M("Comfortable Mystery", "Comfortable%20Mystery.mp3"),
        M("Decay", "Decay.mp3"),
        M("Echoes of Time", "Echoes%20of%20Time.mp3"),
        M("Gathering Darkness", "Gathering%20Darkness.mp3"),
        M("Ghost Processional", "Ghost%20Processional.mp3"),
        M("Heart of Nowhere", "Heart%20of%20Nowhere.mp3"),
        M("Ice Demon", "Ice%20Demon.mp3"),
        M("Night Break", "Night%20Break.mp3"),
        M("Phantasm", "Phantasm.mp3"),
        M("Redletter", "Redletter.mp3"),
        M("Supernatural", "Supernatural.mp3"),
        M("Terminal", "Terminal.mp3"),
        M("The House of Leaves", "The%20House%20of%20Leaves.mp3"),
      ],
    },
    psych: {
      name: "Psych",
      tag: "a trip through the melting vault",
      tracks: [
        M("Deliberate Thought", "Deliberate%20Thought.mp3"),
        M("Lightless Dawn", "Lightless%20Dawn.mp3"),
        M("Dreamlike", "Dreamlike.mp3"),
        M("Thunder Dreams", "Thunder%20Dreams.mp3"),
        M("Spacial Harvest", "Spacial%20Harvest.mp3"),
        M("Ossuary 6 - Air", "Ossuary%206%20-%20Air.mp3"),
        M("Mesmerize", "Mesmerize.mp3"),
        M("Frozen Star", "Frozen%20Star.mp3"),
        M("Fluidscape", "Fluidscape.mp3"),
        M("Evening Fall", "Evening%20Fall.mp3"),
        M("Clean Soul", "Clean%20Soul.mp3"),
        M("Sovereign", "Sovereign.mp3"),
        M("With a Stamp", "With%20a%20Stamp.mp3"),
        M("Cryptic Sorrow", "Cryptic%20Sorrow.mp3"),
        M("Disquiet", "Disquiet.mp3"),
        M("Evening Melodrama", "Evening%20Melodrama.mp3"),
        M("Frozen Will", "Frozen%20Will.mp3"),
        M("Longing Conduct", "Longing%20Conduct.mp3"),
        M("Memory Lane", "Memory%20Lane.mp3"),
        M("Whispering Through", "Whispering%20Through.mp3"),
      ],
    },
    abyss: {
      name: "Abyss",
      tag: "forty fathoms down in the sunken treasury",
      tracks: [
        M("Montauk Point", "Montauk%20Point.mp3"),
        M("Ossuary 5 - Rest", "Ossuary%205%20-%20Rest.mp3"),
        M("Sovereign", "Sovereign.mp3"),
        M("Echoes of Time", "Echoes%20of%20Time.mp3"),
        M("Earnest", "Earnest.mp3"),
        M("Lost Frontier", "Lost%20Frontier.mp3"),
        M("Deep Haze", "Deep%20Haze.mp3"),
        M("Long Note Two", "Long%20Note%20Two.mp3"),
        M("Long Note Three", "Long%20Note%20Three.mp3"),
        M("Long Note Four", "Long%20Note%20Four.mp3"),
        M("Air Prelude", "Air%20Prelude.mp3"),
        M("Reaching Out", "Reaching%20Out.mp3"),
        M("Floating Cities", "Floating%20Cities.mp3"),
        M("Wounded", "Wounded.mp3"),
        M("Drone in D", "Drone%20in%20D.mp3"),
        M("Garden Music", "Garden%20Music.mp3"),
        M("Heavy Interlude", "Heavy%20Interlude.mp3"),
        M("Light Awash", "Light%20Awash.mp3"),
        M("Mirage", "Mirage.mp3"),
        M("Sinking Ship", "Sinking%20Ship.mp3"),
      ],
    },
    synthwave: {
      name: "Synthwave",
      tag: "midnight drive, chrome horizons & laser grids",
      tracks: [
        M("Electrodoodle", "Electrodoodle.mp3"),
        M("New Direction", "New%20Direction.mp3"),
        M("Funkorama", "Funkorama.mp3"),
        M("Groove Grove", "Groove%20Grove.mp3"),
        M("Disco Medusae", "Disco%20Medusae.mp3"),
        M("Bicycle", "Bicycle.mp3"),
        M("Overcast", "Overcast.mp3"),
        M("Plain Loafer", "Plain%20Loafer.mp3"),
        M("RetroFuture Clean", "RetroFuture%20Clean.mp3"),
        M("RetroFuture Nasty", "RetroFuture%20Nasty.mp3"),
        M("Pop Goes the Weasel", "Pop%20Goes%20the%20Weasel.mp3"),
        M("Quasi Motion", "Quasi%20Motion.mp3"),
        M("Carefree", "Carefree.mp3"),
        M("Cipher", "Cipher.mp3"),
        M("Cut and Run", "Cut%20and%20Run.mp3"),
        M("Future Gladiator", "Future%20Gladiator.mp3"),
        M("Laserpack", "Laserpack.mp3"),
        M("Movement Proposition", "Movement%20Proposition.mp3"),
        M("The Cannery", "The%20Cannery.mp3"),
        M("Welcome to the Show", "Welcome%20to%20the%20Show.mp3"),
      ],
    },
    quiet: {
      name: "Quiet",
      tag: "untitled - notepad, pure stillness",
      tracks: [
        M("Long Note Two", "Long%20Note%20Two.mp3"),
        M("Long Note Three", "Long%20Note%20Three.mp3"),
        M("Long Note Four", "Long%20Note%20Four.mp3"),
        M("Air Prelude", "Air%20Prelude.mp3"),
        M("Reaching Out", "Reaching%20Out.mp3"),
        M("Floating Cities", "Floating%20Cities.mp3"),
        M("Almost in F", "Almost%20in%20F.mp3"),
        M("Bittersweet", "Bittersweet.mp3"),
        M("Calmant", "Calmant.mp3"),
        M("Clear Waters", "Clear%20Waters.mp3"),
        M("Dream Culture", "Dream%20Culture.mp3"),
        M("Healing Water", "Healing%20Water.mp3"),
        M("In Spirit", "In%20Spirit.mp3"),
        M("Morning", "Morning.mp3"),
        M("Peace of Mind", "Peace%20of%20Mind.mp3"),
        M("Relaxing Piano", "Relaxing%20Piano.mp3"),
        M("Silver Blue Light", "Silver%20Blue%20Light.mp3"),
        M("Touching Moments One", "Touching%20Moments%20One.mp3"),
        M("Touching Moments Two", "Touching%20Moments%20Two.mp3"),
        M("Wisps of Whorls", "Wisps%20of%20Whorls.mp3"),
      ],
    },
    construct: {
      name: "Construct",
      tag: "machine code lullabies & falling phosphor",
      tracks: [
        M("Mechanolith", "Mechanolith.mp3"),
        M("Industrial Cinematic", "Industrial%20Cinematic.mp3"),
        M("Volatile Reaction", "Volatile%20Reaction.mp3"),
        M("Darkling", "Darkling.mp3"),
        M("Industrial Music Box", "Industrial%20Music%20Box.mp3"),
        M("Iron Horse", "Iron%20Horse.mp3"),
        M("Junkyard Tribe", "Junkyard%20Tribe.mp3"),
        M("Movement Proposition", "Movement%20Proposition.mp3"),
        M("Pulse", "Pulse.mp3"),
        M("Sci Fi", "Sci%20Fi.mp3"),
        M("Static Motion", "Static%20Motion.mp3"),
        M("Summit", "Summit.mp3"),
        M("The Complex", "The%20Complex.mp3"),
        M("Video Dungeon Crawl", "Video%20Dungeon%20Crawl.mp3"),
        M("Blue Sizzle", "Blue%20Sizzle.mp3"),
        M("Gagool", "Gagool.mp3"),
        M("Hitman", "Hitman.mp3"),
        M("Low Force", "Low%20Force.mp3"),
        M("Master Disorder", "Master%20Disorder.mp3"),
        M("Metaphysik", "Metaphysik.mp3"),
      ],
    },
    xeno: {
      name: "Xeno",
      tag: "bioluminescent transmissions & alien deep field",
      tracks: [
        M("Space 1990", "Space%201990.mp3"),
        M("Starry", "Starry.mp3"),
        M("Crusade", "Crusade.mp3"),
        M("Come Play with Me", "Come%20Play%20with%20Me.mp3"),
        M("Dreams Become Real", "Dreams%20Become%20Real.mp3"),
        M("Silver Blue Light", "Silver%20Blue%20Light.mp3"),
        M("Deep Space", "Deep%20Space.mp3"),
        M("Martian Cowboy", "Martian%20Cowboy.mp3"),
        M("Mystery Bazaar", "Mystery%20Bazaar.mp3"),
        M("Procession of the King", "Procession%20of%20the%20King.mp3"),
        M("Senbazuru", "Senbazuru.mp3"),
        M("Stellar Wind", "Stellar%20Wind.mp3"),
        M("Supernatural", "Supernatural.mp3"),
        M("The Other Side of the Door", "The%20Other%20Side%20of%20the%20Door.mp3"),
        M("Trio for Viola", "Trio%20for%20Viola.mp3"),
        M("Unpromised", "Unpromised.mp3"),
        M("Vanishing", "Vanishing.mp3"),
        M("Wandering", "Wandering.mp3"),
        M("Water Lily", "Water%20Lily.mp3"),
        M("Zero Sum", "Zero%20Sum.mp3"),
      ],
    },
    solaris: {
      name: "Solaris",
      tag: "coronal winds, prominence flares & radiant gold",
      tracks: [
        M("Perspectives", "Perspectives.mp3"),
        M("Touching Moments Five - Pulse", "Touching%20Moments%20Five%20-%20Pulse.mp3"),
        M("Clean Soul", "Clean%20Soul.mp3"),
        M("Wisps of Whorls", "Wisps%20of%20Whorls.mp3"),
        M("Constance", "Constance.mp3"),
        M("Lightless Dawn", "Lightless%20Dawn.mp3"),
        M("Sovereign", "Sovereign.mp3"),
        M("Sunspot", "Sunspot.mp3"),
        M("Dreamer", "Dreamer.mp3"),
        M("Morning Walk", "Morning%20Walk.mp3"),
        M("Carefree", "Carefree.mp3"),
        M("Eternal Hope", "Eternal%20Hope.mp3"),
        M("Fluidscape", "Fluidscape.mp3"),
        M("Horizon", "Horizon.mp3"),
        M("Island Sun", "Island%20Sun.mp3"),
        M("Life of Riley", "Life%20of%20Riley.mp3"),
        M("Living Voyage", "Living%20Voyage.mp3"),
        M("Mining by Moonlight", "Mining%20by%20Moonlight.mp3"),
        M("Pluripotent", "Pluripotent.mp3"),
        M("Uplifting", "Uplifting.mp3"),
      ],
    },
    alchemist: {
      name: "Alchemist",
      tag: "crucible of transmutation & ancient hermetica",
      tracks: [
        M("Teller of the Tales", "Teller%20of%20the%20Tales.mp3"),
        M("Midnight Tale", "Midnight%20Tale.mp3"),
        M("Lord of the Land", "Lord%20of%20the%20Land.mp3"),
        M("Master of the Feast", "Master%20of%20the%20Feast.mp3"),
        M("Pippin the Hunchback", "Pippin%20the%20Hunchback.mp3"),
        M("Trio for Piano, Cello, and Clarinet", "Trio%20for%20Piano,%20Cello,%20and%20Clarinet.mp3"),
        M("Celtic Impulse", "Celtic%20Impulse.mp3"),
        M("Danse Macabre", "Danse%20Macabre.mp3"),
        M("Folk Round", "Folk%20Round.mp3"),
        M("Fiddles McGinty", "Fiddles%20McGinty.mp3"),
        M("Hidden Past", "Hidden%20Past.mp3"),
        M("Highland Tears", "Highland%20Tears.mp3"),
        M("Kings Feast", "Kings%20Feast.mp3"),
        M("Minuet", "Minuet.mp3"),
        M("Moorland", "Moorland.mp3"),
        M("Parting of the Ways", "Parting%20of%20the%20Ways.mp3"),
        M("Road to Moscow", "Road%20to%20Moscow.mp3"),
        M("Shenandoah", "Shenandoah.mp3"),
        M("Thatched Villagers", "Thatched%20Villagers.mp3"),
        M("Village Consort", "Village%20Consort.mp3"),
      ],
    },
    glacier: {
      name: "Glacier",
      tag: "hyperborean frost, crystalline ice & polar auroras",
      tracks: [
        M("Winter Chimes", "Winter%20Chimes.mp3"),
        M("Long Note One", "Long%20Note%20One.mp3"),
        M("Heavy Interlude", "Heavy%20Interlude.mp3"),
        M("Mesmerize", "Mesmerize.mp3"),
        M("Frozen Star", "Frozen%20Star.mp3"),
        M("Almost in F", "Almost%20in%20F.mp3"),
        M("Cold Sober", "Cold%20Sober.mp3"),
        M("Crossing the Divide", "Crossing%20the%20Divide.mp3"),
        M("Frost Waltz", "Frost%20Waltz.mp3"),
        M("Glacial Pulse", "Glacial%20Pulse.mp3"),
        M("Ice Demon", "Ice%20Demon.mp3"),
        M("Northern Lights", "Northern%20Lights.mp3"),
        M("Polar Shift", "Polar%20Shift.mp3"),
        M("Snow Drop", "Snow%20Drop.mp3"),
        M("Sub-Zero", "Sub-Zero.mp3"),
        M("The Snow Queen", "The%20Snow%20Queen.mp3"),
        M("Tundra", "Tundra.mp3"),
        M("Whiteout", "Whiteout.mp3"),
        M("Winter Reflections", "Winter%20Reflections.mp3"),
        M("Wistful", "Wistful.mp3"),
      ],
    },
    valhalla: {
      name: "Valhalla",
      tag: "skaldic verse, dragon fires & the gilded shield",
      tracks: [
        M("Hero Down", "Hero%20Down.mp3"),
        M("Volatile Reaction", "Volatile%20Reaction.mp3"),
        M("The Descent", "The%20Descent.mp3"),
        M("Folk Round", "Folk%20Round.mp3"),
        M("Gloom Horizon", "Gloom%20Horizon.mp3"),
        M("Firesong", "Firesong.mp3"),
        M("Five Armies", "Five%20Armies.mp3"),
        M("Black Vortex", "Black%20Vortex.mp3"),
        M("Clash Defiant", "Clash%20Defiant.mp3"),
        M("Dangerous", "Dangerous.mp3"),
        M("Decadence", "Decadence.mp3"),
        M("Final Count", "Final%20Count.mp3"),
        M("Forging On", "Forging%20On.mp3"),
        M("Heroic Age", "Heroic%20Age.mp3"),
        M("Interloper", "Interloper.mp3"),
        M("Lord of the Land", "Lord%20of%20the%20Land.mp3"),
        M("Movement Proposition", "Movement%20Proposition.mp3"),
        M("Stormfront", "Stormfront.mp3"),
        M("The Pyre", "The%20Pyre.mp3"),
        M("Viking War Cry", "Viking%20War%20Cry.mp3"),
      ],
    },
    dynasty: {
      name: "Dynasty",
      tag: "guzheng silk, erhu & imperial court",
      tracks: [
        M("Cambodian Odyssey", "Cambodian%20Odyssey.mp3"),
        M("Floating Cities", "Floating%20Cities.mp3"),
        M("Eastern Thought", "Eastern%20Thought.mp3"),
        M("Sovereign Quarter", "Sovereign%20Quarter.mp3"),
        M("The Silk Road", "The%20Silk%20Road.mp3"),
        M("Temple of the Manes", "Temple%20of%20the%20Manes.mp3"),
        M("Eastminster", "Eastminster.mp3"),
        M("Ghost Processional", "Ghost%20Processional.mp3"),
        M("Five Armies", "Five%20Armies.mp3"),
        M("Accralate", "Accralate.mp3"),
        M("The Pyre", "The%20Pyre.mp3"),
        M("Master of the Feast", "Master%20of%20the%20Feast.mp3"),
        M("Moorland", "Moorland.mp3"),
        M("Hidden Past", "Hidden%20Past.mp3"),
        M("Garden Music", "Garden%20Music.mp3"),
        M("Cryptic Sorrow", "Cryptic%20Sorrow.mp3"),
        M("Wisps of Whorls", "Wisps%20of%20Whorls.mp3"),
        A("River Meditation", "RiverMeditation.mp3"),
        A("Spanish Summer", "SpanishSummer.mp3"),
        A("Acoustic Meditation", "AcousticMeditation.mp3"),
      ],
    },
    zen: {
      name: "Zen",
      tag: "shakuhachi flute, koto & raked stones",
      tracks: [
        A("River Meditation", "RiverMeditation.mp3"),
        A("Acoustic Meditation", "AcousticMeditation.mp3"),
        M("Meditation Impromptu 01", "Meditation%20Impromptu%2001.mp3"),
        M("Meditation Impromptu 02", "Meditation%20Impromptu%2002.mp3"),
        M("Meditation Impromptu 03", "Meditation%20Impromptu%2003.mp3"),
        M("Gymnopedie No 1", "Gymnopedie%20No%201.mp3"),
        M("Soporific", "Soporific.mp3"),
        M("Mesmerize", "Mesmerize.mp3"),
        M("Frozen Star", "Frozen%20Star.mp3"),
        M("Wistful", "Wistful.mp3"),
        M("Almost in F", "Almost%20in%20F.mp3"),
        M("Fluidscape", "Fluidscape.mp3"),
        M("Deliberate Thought", "Deliberate%20Thought.mp3"),
        M("Clean Soul", "Clean%20Soul.mp3"),
        M("Garden Music", "Garden%20Music.mp3"),
        M("Thinking Music", "Thinking%20Music.mp3"),
        M("Long Note One", "Long%20Note%20One.mp3"),
        M("Long Note Two", "Long%20Note%20Two.mp3"),
        M("Morning Walk", "Morning%20Walk.mp3"),
        M("Island Sun", "Island%20Sun.mp3"),
      ],
    },
    samadhi: {
      name: "Samadhi",
      tag: "sitar, bansuri flute, 528Hz & solfeggio",
      tracks: [
        M("Eastern Thought", "Eastern%20Thought.mp3"),
        M("Temple of the Manes", "Temple%20of%20the%20Manes.mp3"),
        M("Shamanistic", "Shamanistic.mp3"),
        M("Desert City", "Desert%20City.mp3"),
        A("Acoustic Meditation", "AcousticMeditation.mp3"),
        A("River Meditation", "RiverMeditation.mp3"),
        M("Meditation Impromptu 01", "Meditation%20Impromptu%2001.mp3"),
        M("Meditation Impromptu 02", "Meditation%20Impromptu%2002.mp3"),
        M("Meditation Impromptu 03", "Meditation%20Impromptu%2003.mp3"),
        M("Thunder Dreams", "Thunder%20Dreams.mp3"),
        M("Dreamlike", "Dreamlike.mp3"),
        M("Spacial Harvest", "Spacial%20Harvest.mp3"),
        M("Lightless Dawn", "Lightless%20Dawn.mp3"),
        M("Mesmerize", "Mesmerize.mp3"),
        M("Wisps of Whorls", "Wisps%20of%20Whorls.mp3"),
        M("Constance", "Constance.mp3"),
        M("Sovereign", "Sovereign.mp3"),
        M("Evening Fall", "Evening%20Fall.mp3"),
        M("Clean Soul", "Clean%20Soul.mp3"),
        M("Deliberate Thought", "Deliberate%20Thought.mp3"),
      ],
    },
    silkroad: {
      name: "Silk Road",
      tag: "persian santur, desert oud & oasis lofi",
      tracks: [
        M("The Silk Road", "The%20Silk%20Road.mp3"),
        M("Desert City", "Desert%20City.mp3"),
        M("Curse of the Scarab", "Curse%20of%20the%20Scarab.mp3"),
        M("Eastern Thought", "Eastern%20Thought.mp3"),
        M("Sovereign Quarter", "Sovereign%20Quarter.mp3"),
        M("Cambodian Odyssey", "Cambodian%20Odyssey.mp3"),
        M("Mirage", "Mirage.mp3"),
        M("Moorland", "Moorland.mp3"),
        M("Master of the Feast", "Master%20of%20the%20Feast.mp3"),
        M("The Pyre", "The%20Pyre.mp3"),
        M("Floating Cities", "Floating%20Cities.mp3"),
        M("Lost Frontier", "Lost%20Frontier.mp3"),
        M("Airship Serenity", "Airship%20Serenity.mp3"),
        M("Bassa Island", "Bassa%20Island.mp3"),
        M("Tikopia", "Tikopia.mp3"),
        M("Scheming Weasel", "Scheming%20Weasel.mp3"),
        A("Spanish Summer", "SpanishSummer.mp3"),
        A("River Meditation", "RiverMeditation.mp3"),
        A("Acoustic Meditation", "AcousticMeditation.mp3"),
        M("Garden Music", "Garden%20Music.mp3"),
      ],
    },
  };
  window.TITAN_PLAYLIST = window.TITAN_STATIONS.lofi.tracks;
  window.TITAN_STATION_ORDER = [
    "lofi", "classical", "epic", "jazz", "adventure", "dark", "psych",
    "abyss", "synthwave", "quiet", "construct", "xeno",
    "solaris", "alchemist", "glacier", "valhalla",
    "dynasty", "zen", "samadhi", "silkroad"
  ];
})();
