/* Titan Reliquary · Health view (#health) and the truthful Refresh button.
   Shows which build and data this page is really running, whether a newer one is published, the offline copy,
   the collection counts (data/status.json, generated by the pipeline: never typed here) and a 3-second speed test.
   Refresh: TitanHealth.refresh() checks version.json (no-store) and says what happened: "Updating to trNN",
   "Updated to trNN (data published ...)" after the reload, "Already up to date", or "Can't check right now".
   Reached by #health or the Health button in the Hall footer. Styles: styles/health.css (own high-contrast palette).
   API: TitanHealth.open(), .close(), .refresh(), .report() (plain-text summary), ._compare(remote). */
(function () {
  "use strict";
  let root = null, lastFocus = null, toastEl = null, toastTimer = 0, speed = null, lastReport = "";
  const FLAG = "titan.refreshMsg";

  const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const n = (v) => (v == null || v === "" ? "?" : Number(v).toLocaleString("en-US"));

  /* The app build is the ?v= on this very script tag (every script and style carries the same stamp). */
  function appBuild() {
    try {
      const s = document.querySelector('script[src*="wings/health.js"]');
      const m = s && String(s.getAttribute("src")).match(/[?&]v=([^&]+)/);
      if (m) return m[1];
    } catch (e) { /* ignore */ }
    return "?";
  }
  function runningPublish() {
    const v = window.vault;
    return (v && (v.generated_at || v.generated_at_pt)) || "";
  }
  function when(iso) {
    const t = Date.parse(iso);
    if (!Number.isFinite(t)) return iso ? String(iso) : "unknown";
    const d = new Date(t), mins = Math.round((Date.now() - t) / 60000);
    let ago;
    if (mins < 1) ago = "just now"; else if (mins < 60) ago = mins + " minute" + (mins === 1 ? "" : "s") + " ago";
    else if (mins < 2880) { const h = Math.round(mins / 60); ago = h + " hour" + (h === 1 ? "" : "s") + " ago"; }
    else { const dd = Math.round(mins / 1440); ago = dd + " days ago"; }
    return d.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) + " (" + ago + ")";
  }
  function whenShort(iso) {
    const t = Date.parse(iso);
    return Number.isFinite(t) ? new Date(t).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : (iso || "unknown");
  }
  /* fresh: refuse a copy the service worker served from its saved cache because the network failed (marked by sw.js),
     so "Up to date" is never claimed from an old saved copy. */
  function getJSON(url, fresh) {
    return fetch(url + (url.includes("?") ? "&" : "?") + "t=" + Date.now(), { cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error(url + " " + r.status);
        if (fresh && r.headers.get("x-titan-from-cache")) throw new Error("saved copy only");
        return r.json();
      });
  }
  function lastCheck() { try { const v = localStorage.getItem("titan.lastVersionCheck"); return v ? Number(v) : 0; } catch (e) { return 0; } }
  function noteCheck() { try { localStorage.setItem("titan.lastVersionCheck", String(Date.now())); } catch (e) { /* blocked */ } }

  /* Compare a fetched version.json with what is running. */
  function compare(remote) {
    const rb = remote && remote.build, ab = appBuild();
    const rp = remote && (remote.generated_at || remote.generated_at_pt || ""), cp = runningPublish();
    const buildNewer = !!(rb && ab !== "?" && rb !== ab);
    const rt = Date.parse(rp), ct = Date.parse(cp);
    const dataNewer = Number.isFinite(rt) && Number.isFinite(ct) ? rt - ct > 120000 : !!(rp && cp && rp !== cp);
    return { newer: buildNewer || dataNewer, buildNewer, dataNewer, build: rb || ab, publish: rp };
  }

  /* ---------- the toast that says what happened ---------- */
  function say(msg, sticky) {
    if (!toastEl) {
      toastEl = document.createElement("div");
      toastEl.id = "health-toast"; toastEl.className = "health-toast";
      toastEl.setAttribute("role", "status"); toastEl.setAttribute("aria-live", "polite");
      document.body.appendChild(toastEl);
    }
    clearTimeout(toastTimer);
    toastEl.textContent = msg; toastEl.hidden = false;
    if (!sticky) toastTimer = setTimeout(() => { toastEl.hidden = true; }, 9000);
  }

  async function swUpdate() {
    try {
      const reg = await navigator.serviceWorker.getRegistration();
      if (reg) await Promise.race([reg.update(), new Promise((r) => setTimeout(r, 3000))]);
    } catch (e) { /* offline or no SW */ }
  }
  function applyUpdate(c) {
    try { sessionStorage.setItem(FLAG, JSON.stringify({ build: c.build, publish: c.publish })); } catch (e) { /* ignore */ }
    swUpdate().finally(() => { if (window.TitanReload) window.TitanReload(); else location.reload(); });
  }

  async function refresh() {
    const btn = document.getElementById("btn-refresh");
    if (btn) btn.disabled = true;
    try {
      let remote;
      try {
        if (navigator.onLine === false) throw new Error("offline");
        remote = await getJSON("version.json", true); noteCheck();
      }
      catch (e) {
        const lc = lastCheck(), saved = runningPublish();
        say("Can't check right now: " + (navigator.onLine === false ? "you are offline" : "the site did not answer") + ". Showing the saved copy from " + whenShort(saved || (lc ? new Date(lc).toISOString() : "")) + ".");
        return { ok: false };
      }
      const c = compare(remote);
      if (c.newer) {
        say("Updating to " + c.build + (c.buildNewer ? "" : " (new data)") + "…", true);
        applyUpdate(c);
        return { ok: true, updating: true };
      }
      say("Already up to date (" + appBuild() + ", data " + whenShort(runningPublish() || remote.generated_at) + ").");
      return { ok: true, updating: false };
    } finally { if (btn) btn.disabled = false; }
  }

  function showAfterReload() {
    let f = null;
    try { f = sessionStorage.getItem(FLAG); sessionStorage.removeItem(FLAG); } catch (e) { return; }
    if (!f) return;
    try { const o = JSON.parse(f); say("Updated to " + (appBuild() !== "?" ? appBuild() : o.build) + " (data published " + whenShort(runningPublish() || o.publish) + ").", false); } catch (e) { /* ignore */ }
  }

  /* ---------- gathering ---------- */
  function swInfo() {
    return new Promise((resolve) => {
      if (!("serviceWorker" in navigator)) return resolve({ state: "not supported" });
      const ctl = navigator.serviceWorker.controller;
      if (!ctl) return resolve({ state: "not active yet" });
      const ch = new MessageChannel(), t = setTimeout(() => resolve({ state: "no answer" }), 2500);
      ch.port1.onmessage = (e) => { clearTimeout(t); resolve({ state: "active", build: e.data && e.data.build, caches: (e.data && e.data.caches) || [] }); };
      try { ctl.postMessage({ type: "titan:sw-info" }, [ch.port2]); } catch (e) { clearTimeout(t); resolve({ state: "no answer" }); }
    });
  }
  async function cacheCounts() {
    const out = [];
    try {
      for (const k of await caches.keys()) { const c = await caches.open(k); out.push({ name: k, count: (await c.keys()).length }); }
    } catch (e) { /* no cache API */ }
    return out;
  }
  /* ---------- background jobs (fix list #49): the repo's GitHub Actions, read from the public API (no sign-in, 60 requests/hour) ---------- */
  const REPO = "jpavia10/titan-reliquary-preview";
  const JOBS = [
    { name: "prices", label: "Daily gold and silver price", what: "Fetches today's price every evening" },
    { name: "pages build and deployment", label: "Publishing the app", what: "Puts each new version online" },
    { name: "verify-live", label: "Live check after publishing", what: "Checks the online copy matches what was published" },
    { name: "smoke", label: "Whole-app test", what: "Opens every part of the app after each change" },
    { name: "backup-zip", label: "Site backup", what: "Builds the backup copy for Drive" },
  ];
  function jobRuns() {
    const ctl = typeof AbortController === "function" ? new AbortController() : null;
    const t = setTimeout(() => { try { ctl && ctl.abort(); } catch (e) { /* ignore */ } }, 6000);
    return fetch(`https://api.github.com/repos/${REPO}/actions/runs?per_page=60`, { cache: "no-store", signal: ctl ? ctl.signal : undefined })
      .then((r) => { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
      .then((d) => JOBS.map((j) => {
        const runs = (d.workflow_runs || []).filter((x) => x.name === j.name && x.status === "completed" && x.conclusion !== "cancelled" && x.conclusion !== "skipped");
        const last = runs[0];
        return Object.assign({}, j, last ? { conclusion: last.conclusion, at: last.updated_at || last.created_at, url: last.html_url } : { conclusion: null });
      }))
      .finally(() => clearTimeout(t));
  }
  function markHealthButton(jobs) {
    const b = document.getElementById("btn-health");
    if (!b || !jobs) return;
    const bad = jobs.filter((j) => j.conclusion && j.conclusion !== "success").length;
    b.textContent = bad ? `Health ⚠ ${bad}` : "Health";
    b.title = bad ? `${bad} background job${bad === 1 ? "" : "s"} failed: open Health` : "";
  }

  async function gather() {
    const g = { app: appBuild(), publish: runningPublish(), online: navigator.onLine !== false, lastCheck: lastCheck() };
    const [sw, cc, status, remote, jobs] = await Promise.all([
      swInfo(), cacheCounts(),
      getJSON("data/status.json").catch(() => null),
      getJSON("version.json", true).then((v) => { noteCheck(); g.lastCheck = Date.now(); return v; }).catch(() => null),
      g.online ? jobRuns().catch(() => null) : Promise.resolve(null),
    ]);
    g.sw = sw; g.caches = cc; g.status = status; g.remote = remote; g.jobs = jobs; markHealthButton(jobs);
    g.cmp = remote ? compare(remote) : null;
    if (!g.publish && status) g.publish = status.generated_at;
    return g;
  }

  /* ---------- rendering ---------- */
  /* a plain progress bar: the text next to it always says the number (#57, #75) */
  function bar(a, b) { const pc = b ? Math.max(0, Math.min(100, (100 * a) / b)) : 0; return `<span class="hv-bar" role="img" aria-hidden="true"><i style="width:${pc.toFixed(1)}%"></i></span>`; }
  const P1_WORDS = { photo: "a phone photo", country: "the country", year: "the year", denomination: "the denomination", mint: "the mint mark read", story: "a story", value: "a default value" };
  const AI_NAMES = { grok: "Grok", muse: "Muse", gemini: "Gemini", chatgpt: "ChatGPT", claude: "Claude" };
  function loopText(l) {
    const open = Object.entries(l.open_assignments || {}).filter(([, c]) => c).map(([a, c]) => (AI_NAMES[a] || a) + " " + c).join(", ");
    const chk = Object.entries(l.checked_by_another || {}).map(([a, r]) => (AI_NAMES[a] || a) + ": " + n(r.checked) + " of its facts checked by another AI, " + n(r.wrong) + " wrong").join("; ");
    return "Homework is handed out from the data after every update: " + (open || "none open") + ". Every AI fact is checked by a different AI." + (chk ? " " + chk + "." : "");
  }
  function p1left(p) { const m = Object.entries(p.missing || {}).filter(([, c]) => c); return m.length ? m.map(([k, c]) => n(c) + " need " + (P1_WORDS[k] || k)).join(", ") : "nothing"; }
  function row(k, v, sub) { return `<div class="hv-row"><dt>${esc(k)}</dt><dd>${v}${sub ? `<small>${esc(sub)}</small>` : ""}</dd></div>`; }
  function render(g) {
    const s = g.status, L = [];   // L = plain-text report lines
    const out = [];
    L.push("Titan Reliquary health report", "Page: " + location.href.split("#")[0], "Time: " + new Date().toString());
    // You are looking at
    const swTxt = g.sw.state === "active" ? (g.sw.build || "?") : "not running (" + g.sw.state + ")";
    const dataBuild = s ? s.build : (g.remote && g.remote.build) || "?";
    const hash = s ? String(s.collection_hash).slice(0, 12) : (g.remote && g.remote.content_hash) || "?";
    out.push(`<section class="hv-sec" aria-labelledby="hv-h-now"><h2 id="hv-h-now">You are looking at</h2><dl>
      ${row("App version", esc(g.app), "The program code running in this page.")}
      ${row("Offline helper version", esc(swTxt), "The background helper that keeps a saved copy for when you have no internet.")}
      ${row("Data version", esc(dataBuild) + " &middot; " + esc(hash), "Which publish of the coin list this is.")}
      ${row("Data published", esc(when(g.publish)))}
    </dl></section>`);
    L.push("", "YOU ARE LOOKING AT", "App build: " + g.app, "Service worker build: " + swTxt, "Data build: " + dataBuild + ", collection hash " + hash, "Data published: " + when(g.publish));
    // Newest?
    let newest, nl, cls = "ok";
    if (!g.cmp) { newest = "Can't check right now" + (g.online ? "." : ": you are offline."); nl = newest; cls = "warn"; }
    else if (g.cmp.newer) {
      cls = "warn";
      newest = `A newer version (${esc(g.cmp.build)}) is available. <button type="button" class="hv-btn hv-primary" data-update>Update now</button>`;
      nl = "A newer version (" + g.cmp.build + ") is available";
    } else { newest = "Up to date"; nl = "Up to date"; }
    out.push(`<section class="hv-sec" aria-labelledby="hv-h-new"><h2 id="hv-h-new">Is it the newest?</h2>
      <p class="hv-status hv-${cls}">${newest}</p>
      <p class="hv-sub">Checked just now against the published copy.</p></section>`);
    L.push("", "IS IT THE NEWEST?", nl);
    // Offline
    const cl = g.caches.length ? g.caches.map((c) => `<li>${esc(c.name)}: ${n(c.count)} items</li>`).join("") : "<li>No saved copy yet</li>";
    out.push(`<section class="hv-sec" aria-labelledby="hv-h-off"><h2 id="hv-h-off">Offline copy</h2><dl>
      ${row("Connection", g.online ? "Online" : "Offline", g.online ? "" : "Showing the saved copy.")}
      ${window.TitanMotion ? row("Motion", esc({ full: "Full", calm: "Calm", off: "Off" }[window.TitanMotion.level()] || "?") + (window.TitanMotion.choice() ? "" : " (following this phone's setting)"), "Change it in Scene Studio, Settings.") : ""}
      ${window.TitanHaptics && window.TitanHaptics.supported() ? row("Vibrate on taps", window.TitanHaptics.enabled() ? "On" : "Off", "Change it in Scene Studio, Settings.") : ""}
      ${row("Last successful check", g.lastCheck ? esc(when(new Date(g.lastCheck).toISOString())) : "never", "When this device last asked for the newest version.")}
    </dl><p class="hv-label">Saved copies on this device</p><ul class="hv-list">${cl}</ul>
      ${window.TitanWarm ? `<button type="button" class="hv-btn" data-warm>Save all coin photos for offline (about 10 MB)</button><p class="hv-status" id="hv-warm" aria-live="polite">Coin details and search are saved automatically; photos are saved when first seen, or all at once with this button.</p>` : ""}</section>`);
    L.push("", "OFFLINE COPY", "Online: " + (g.online ? "yes" : "no"), "Motion: " + (window.TitanMotion ? window.TitanMotion.level() + (window.TitanMotion.choice() ? "" : " (phone setting)") : "?") + ", haptics " + (window.TitanHaptics ? (window.TitanHaptics.supported() ? (window.TitanHaptics.enabled() ? "on" : "off") : "not supported") : "?"), "Last version check: " + (g.lastCheck ? when(new Date(g.lastCheck).toISOString()) : "never"),
      ...g.caches.map((c) => "Cache " + c.name + ": " + c.count + " entries"));
    // Collection
    if (!s) {
      out.push(`<section class="hv-sec" aria-labelledby="hv-h-col"><h2 id="hv-h-col">Collection</h2><p class="hv-status hv-warn">Status not published yet</p></section>`);
      L.push("", "COLLECTION", "Status not published yet");
    } else {
      const p = s.photos || {}, r = s.research || {}, ig = s.integrity || {}, sp = s.specimens || {};
      const probs = Number(ig.problems) || 0;
      out.push(`<section class="hv-sec" aria-labelledby="hv-h-col"><h2 id="hv-h-col">Collection</h2><dl>
        ${row("Coins and tokens", n(sp.coins) + " coins, " + n(sp.tokens) + " tokens", n(sp.total) + " in all, from " + n(s.countries) + " countries.")}
        ${row("Phone photos", n(p.specimens_with_any) + " of " + n(sp.total), n(p.still_needed) + " still need a phone photo. Pro photos (Phase 2): " + n(p.phase2_specimens) + ".")}
        ${row("Open questions", n(r.open_questions), "On " + n(r.specimens_with_open_questions) + " coins, still being checked.")}
        ${s.phase1 ? row("Phase 1 finish line", bar(s.phase1.done, s.phase1.total) + n(s.phase1.done) + " of " + n(s.phase1.total) + " pieces (" + s.phase1.pct + " %)", "Through Phase 1 = photo, country, year, denomination, mint mark read, story and default value. Still to do: " + p1left(s.phase1) + ". The Lab lists each piece.") : ""}
        ${s.trust ? row("How sure we are", bar(s.trust.cited_or_confirmed, s.trust.facts) + s.trust.pct_cited + " % cited or confirmed", n(s.trust.cited_or_confirmed) + " of " + n(s.trust.facts) + " facts have an exact source or your confirmation" + (s.trust.pct_checked ? " (" + s.trust.pct_checked + " % checked by two independent sources)" : "") + "; " + s.trust.pct_photo + " % were read from a photo, " + s.trust.pct_ai + " % an AI said without a source yet, " + s.trust.pct_ledger + " % came from the original ledger unchecked, " + s.trust.pct_review + " % are being checked.") : ""}
        ${s.loop ? row("The other AIs at work", n(Object.values(s.loop.open_assignments || {}).reduce((x, y) => x + y, 0)) + " homework assignments open", loopText(s.loop)) : ""}
        ${s.chain ? row("Change history", n(s.chain.lines) + " changes, sealed", "Every change is chained to the one before it (fingerprint " + String(s.chain.tip || "").slice(0, 12) + "), so the history cannot be quietly rewritten: a correction is always a new line.") : ""}
        ${s.truth ? row("Contradictions to check", n(s.truth.total), s.truth.total ? "Records that disagree with each other or claim more than their evidence: " + Object.entries(s.truth.by_rule || {}).map(([k, c]) => c + " " + k.replace(/_/g, " ")).join(", ") + "." : "None found.") : ""}
      </dl><p class="hv-status ${probs ? "hv-bad" : "hv-ok"}">${probs ? n(probs) + " problem" + (probs === 1 ? "" : "s") + " found" : "No problems found"}</p>
      ${ig.warnings ? `<p class="hv-sub">${n(ig.warnings)} minor warning${ig.warnings === 1 ? "" : "s"}.</p>` : ""}</section>`);
      L.push("", "COLLECTION", n(sp.coins) + " coins, " + n(sp.tokens) + " tokens, " + n(s.countries) + " countries",
        "Phone photo: " + n(p.specimens_with_any) + " of " + n(sp.total) + " (" + n(p.still_needed) + " need one; Phase 2: " + n(p.phase2_specimens) + ")",
        "Open research questions: " + n(r.open_questions) + " on " + n(r.specimens_with_open_questions) + " coins",
        "Integrity: " + (probs ? probs + " problems" : "no problems") + ", " + n(ig.warnings || 0) + " warnings",
        "Phase 1 finish line: " + (s.phase1 ? s.phase1.done + " of " + s.phase1.total + " (" + s.phase1.pct + " %); left: " + p1left(s.phase1) : "not published"),
        "Trust: " + (s.trust ? s.trust.cited_or_confirmed + " of " + s.trust.facts + " facts cited or confirmed (" + s.trust.pct_cited + " %) " + JSON.stringify(s.trust.by_level || {}) : "not published"),
        "Contradictions to check: " + (s.truth ? s.truth.total + " " + JSON.stringify(s.truth.by_rule || {}) : "not published"),
        "Research loop: " + (s.loop ? JSON.stringify(s.loop.open_assignments || {}) + " open; pools " + JSON.stringify(s.loop.pools || {}) : "not published"),
        "Change history: " + (s.chain ? s.chain.lines + " lines, tip " + s.chain.tip : "not chained"));
    }
    // Background jobs (#49)
    if (!g.jobs) {
      out.push(`<section class="hv-sec" aria-labelledby="hv-h-jobs"><h2 id="hv-h-jobs">Background jobs</h2><p class="hv-status hv-warn">Can't check right now${g.online ? "" : ": you are offline"}.</p></section>`);
      L.push("", "BACKGROUND JOBS", "Can't check right now");
    } else {
      const bad = g.jobs.filter((j) => j.conclusion && j.conclusion !== "success");
      const word = (j) => (!j.conclusion ? "No run yet" : j.conclusion === "success" ? "Worked" : "FAILED");
      out.push(`<section class="hv-sec" aria-labelledby="hv-h-jobs"><h2 id="hv-h-jobs">Background jobs</h2>
        <p class="hv-status ${bad.length ? "hv-bad" : "hv-ok"}">${bad.length ? `${bad.length} job${bad.length === 1 ? "" : "s"} failed last time. Tell Claude.` : "All working"}</p><dl>
        ${g.jobs.map((j) => row(j.label, `<span class="${!j.conclusion ? "" : j.conclusion === "success" ? "hv-ok" : "hv-bad"}">${word(j)}</span>${j.at ? " &middot; " + esc(when(j.at)) : ""}`, j.what)).join("")}
      </dl></section>`);
      L.push("", "BACKGROUND JOBS", ...g.jobs.map((j) => j.label + ": " + word(j) + (j.at ? " (" + j.at + ")" : "") + (j.conclusion && j.conclusion !== "success" && j.url ? " " + j.url : "")));
    }
    // Speed
    out.push(`<section class="hv-sec" aria-labelledby="hv-h-spd"><h2 id="hv-h-spd">Speed</h2>
      <p class="hv-sub">Press the button, then leave the screen alone for 3 seconds. Smooth is 55 or more.</p>
      <button type="button" class="hv-btn" data-speed>Measure speed</button>
      <p class="hv-status" id="hv-speed" aria-live="polite">${speed ? esc(speedText(speed)) : "Not measured yet"}</p></section>`);
    out.push(`<section class="hv-sec"><button type="button" class="hv-btn hv-primary" data-copy>Copy report</button>
      <p class="hv-status" id="hv-copied" aria-live="polite"></p>
      <textarea id="hv-report" class="hv-report" readonly rows="10" aria-label="Plain text report" hidden></textarea></section>`);
    lastReport = L.join("\n");
    root.querySelector("#hv-body").innerHTML = out.join("");
    updateSpeedInReport();
  }
  function speedWord(f) { return f >= 55 ? "smooth" : f >= 40 ? "a bit slow" : "slow"; }
  function speedText(f) { return Math.round(f) + " frames per second: " + speedWord(f); }
  function updateSpeedInReport() { if (speed) lastReport = lastReport.replace(/\n*SPEED:[\s\S]*$/, "") + "\n\nSPEED: " + speedText(speed); }

  function measure() {
    const out = root.querySelector("#hv-speed"), btn = root.querySelector("[data-speed]");
    btn.disabled = true; out.textContent = "Measuring…";
    let frames = 0, t0 = 0;
    function tick(t) {
      if (!t0) t0 = t;
      frames++;
      if (t - t0 < 3000) return requestAnimationFrame(tick);
      speed = frames / ((t - t0) / 1000);
      out.textContent = speedText(speed); btn.disabled = false; updateSpeedInReport();
    }
    requestAnimationFrame(tick);
  }
  async function copy() {
    const msg = root.querySelector("#hv-copied"), ta = root.querySelector("#hv-report");
    ta.value = lastReport;
    try { await navigator.clipboard.writeText(lastReport); msg.textContent = "Copied. Paste it into your message."; }
    catch (e) {
      ta.hidden = false; ta.focus(); ta.select();
      try { document.execCommand("copy"); msg.textContent = "Copied. Paste it into your message."; }
      catch (e2) { msg.textContent = "Could not copy by itself. The text is selected: copy it by hand."; }
    }
  }

  /* ---------- view ---------- */
  function lum(c) {
    const m = String(c || "").trim().match(/^#([0-9a-f]{3,8})$/i); if (!m) return null;
    let h = m[1]; if (h.length < 6) h = h.split("").map((x) => x + x).join("");
    return (0.2126 * parseInt(h.slice(0, 2), 16) + 0.7152 * parseInt(h.slice(2, 4), 16) + 0.0722 * parseInt(h.slice(4, 6), 16)) / 255;
  }
  function applyTone() {
    if (!root) return;
    let l = null;
    try { l = lum(getComputedStyle(document.documentElement).getPropertyValue("--bg")); } catch (e) { /* ignore */ }
    if (l == null) l = window.matchMedia && matchMedia("(prefers-color-scheme: light)").matches ? 1 : 0;
    root.dataset.tone = l > 0.5 ? "light" : "dark";
  }
  function build() {
    root = document.createElement("div");
    root.id = "health-view"; root.className = "health-view"; root.hidden = true;
    root.setAttribute("role", "dialog"); root.setAttribute("aria-modal", "true"); root.setAttribute("aria-labelledby", "hv-title");
    root.innerHTML = `<div class="hv-shell">
      <div class="hv-top"><h1 id="hv-title" tabindex="-1">About this copy</h1>
        <button type="button" class="hv-btn" data-close>Close</button></div>
      <p class="hv-sub">What this copy of the app is, whether it is the newest, and whether the collection looks healthy.</p>
      <div id="hv-body"><p class="hv-status">Looking…</p></div></div>`;
    document.body.appendChild(root);
    root.addEventListener("click", (e) => {
      const t = e.target;
      if (t.closest("[data-close]")) return close(true);
      if (t.closest("[data-speed]")) return measure();
      if (t.closest("[data-copy]")) return copy();
      if (t.closest("[data-warm]")) {
        const o = root.querySelector("#hv-warm"), b = t.closest("[data-warm]"); b.disabled = true; if (o) o.textContent = "Saving… keep this screen open.";
        return window.TitanWarm(true).then((r) => { b.disabled = false; if (o) o.textContent = r && r.ok ? `Done: ${r.photos} new photo(s) and ${r.data} data file(s) saved. Everything opens offline now.` : "Could not save right now (offline?). Try again when online."; });
      }
      if (t.closest("[data-update]")) { say("Updating…", true); return applyUpdate(root._g && root._g.cmp); }
    });
    root.addEventListener("keydown", (e) => { if (e.key === "Escape") close(true); });
  }
  function open() {
    if (!root) build();
    if (!root.hidden) return;
    lastFocus = document.activeElement; applyTone();
    root.hidden = false; document.body.style.overflow = "hidden"; root.scrollTop = 0;
    root.querySelector("#hv-title").focus({ preventScroll: true });
    gather().then((g) => { root._g = g; if (!root.hidden) render(g); });
  }
  function close(navigate) {
    if (!root || root.hidden) return;
    root.hidden = true; document.body.style.overflow = "";
    if (navigate && /^#health/i.test(location.hash)) location.hash = "hall";
    if (lastFocus && lastFocus.focus) { try { lastFocus.focus(); } catch (e) { /* gone */ } }
  }
  function route() { if (/^#health(\b|$)/i.test(location.hash)) open(); else close(false); }
  window.addEventListener("hashchange", route);
  window.addEventListener("titan:atmo", applyTone);
  window.TitanHealth = { open, close, refresh, report: () => lastReport, _compare: compare };
  function boot() {
    route();
    // one quiet background-jobs check per session, so the Hall's Health button can show a warning (#49)
    let cached = null;
    try { cached = JSON.parse(sessionStorage.getItem("titan.jobs") || "null"); } catch (e) { /* storage blocked */ }
    if (cached) markHealthButton(cached);
    else if (navigator.onLine !== false) setTimeout(() => jobRuns().then((j) => { markHealthButton(j); try { sessionStorage.setItem("titan.jobs", JSON.stringify(j)); } catch (e) { /* ignore */ } }).catch(() => {}), 4000);
    // vault (data/index.json) loads after this script: wait for it so "data published" is the real one
    let tries = 0;
    (function wait() { if (window.vault || ++tries > 40) showAfterReload(); else setTimeout(wait, 250); })();
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
})();
