#!/usr/bin/env python3
"""AI cost against facts produced (fix list #20): one line per AI change file, written to collaborators/AI_RUNS.md.

  python3 tools/pipeline/ai_runs.py            (run at every intake, after publish.py; it never runs inside publish)

Per file in collection/_incoming/applied/ (and rejected files' .report.txt next to them):
  events   lines in the file
  kept     events that reached collection/changes.jsonl (same ts, by, entity, id, field)
  dropped  the rest (no change, superseded, re-filed by Claude, or the whole file rejected)
  cost     provenance.cost_usd summed over the file's events ("-" when the contributor did not report it; schema: INSTRUCTIONS.md section 2)
  tokens   provenance.tokens summed the same way
The goal is verified facts per dollar; verified (owner-confirmed) facts are counted from the owner's later confirmations of those same fields.
Re-filed files (an AI's off-contract file that Claude rewrote as changes_claude_*) count under the AI named in the REFILED note.
"""
import collections, glob, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APPLIED = os.path.join(ROOT, "collection", "_incoming", "applied")
OUT = os.path.join(ROOT, "collaborators", "AI_RUNS.md")


def key(e): return (e.get("ts"), e.get("by"), e.get("entity"), e.get("id"), e.get("field"))


def read_lines(p):
    out = []
    for l in open(p, encoding="utf-8"):
        l = l.strip()
        if not l: continue
        try: out.append(json.loads(l))
        except ValueError: out.append({})
    return out


def runs():
    log = read_lines(os.path.join(ROOT, "collection", "changes.jsonl"))
    logged = {key(e) for e in log}
    verified_at = collections.defaultdict(list)          # (entity, id, field) -> owner verified ts
    for e in log:
        if e.get("by") == "owner" and e.get("verified"): verified_at[(e.get("entity"), e.get("id"), e.get("field"))].append(e.get("ts") or "")
    refiled = {}
    for n in glob.glob(os.path.join(APPLIED, "*REFILED*")):
        txt = open(n, encoding="utf-8").read()
        for m in re.finditer(r"(changes_claude_\d{8}-\d{4}\.jsonl)", txt):
            src = re.findall(r"changes_(muse|grok|gemini)_", txt)
            if src: refiled[m.group(1)] = src[0]
    rows = []
    for p in sorted(glob.glob(os.path.join(APPLIED, "changes_*.jsonl"))):
        name = os.path.basename(p)
        m = re.match(r"changes_([a-z0-9-]+)_(\d{8})-(\w+?)(?:[_.-].*)?\.jsonl$", name)
        agent = m.group(1) if m else "?"
        if agent in ("script", "owner"): continue
        evs = read_lines(p)
        kept = [e for e in evs if key(e) in logged]
        models = sorted({e.get("by", "?") for e in evs})
        prov = [e.get("provenance") or {} for e in evs]
        cost = sum(float(x.get("cost_usd") or 0) for x in prov) if any(x.get("cost_usd") is not None for x in prov) else None
        tokens = sum(int(x.get("tokens") or 0) for x in prov) if any(x.get("tokens") is not None for x in prov) else None
        ver = sum(1 for e in kept if any(t > (e.get("ts") or "") for t in verified_at.get((e.get("entity"), e.get("id"), e.get("field")), [])))
        rows.append({"file": name, "date": f"{m.group(2)[:4]}-{m.group(2)[4:6]}-{m.group(2)[6:]}" if m else "?", "agent": refiled.get(name, agent) + (" (re-filed by Claude)" if name in refiled else ""),
                     "models": ", ".join(models), "events": len(evs), "kept": len(kept), "verified": ver, "cost": cost, "tokens": tokens,
                     "provenance": sum(1 for x in prov if x)})
    for rep in sorted(glob.glob(os.path.join(APPLIED, "*.report.txt")) + glob.glob(os.path.join(ROOT, "collection", "_incoming", "rejected", "*.jsonl"))):
        name = os.path.basename(rep).replace(".report.txt", "")
        if any(r["file"] == name for r in rows): continue
        rows.append({"file": name, "date": "?", "agent": name.split("_")[1] if "_" in name else "?", "models": "", "events": 0, "kept": 0, "verified": 0,
                     "cost": None, "tokens": None, "provenance": 0, "rejected": True})
    return rows


def main():
    rows = runs()
    by_agent = collections.defaultdict(lambda: {"files": 0, "events": 0, "kept": 0, "verified": 0, "cost": 0.0, "costed": 0})
    for r in rows:
        a = by_agent[r["agent"].split(" ")[0]]
        a["files"] += 1; a["events"] += r["events"]; a["kept"] += r["kept"]; a["verified"] += r["verified"]
        if r["cost"] is not None: a["cost"] += r["cost"]; a["costed"] += 1
    money = lambda c: "-" if c is None else f"${c:,.2f}"
    lines = ["<!-- doc-status: current; normative: no -->", "# AI runs: cost against facts produced (fix list #20)", "",
             "Generated by `python3 tools/pipeline/ai_runs.py` at each intake; do not edit by hand. One line per AI change file.",
             "**kept** = events that reached the collection's change log; **verified** = of those, facts the owner later confirmed.",
             "**cost** comes from each event's `provenance.cost_usd`; `-` means the contributor did not report it (ask for it: INSTRUCTIONS.md section 2).",
             "Contribution quality (follows the rules) is scored in `CONTRIBUTOR_SCORES.md`; accuracy against known answers in `MODEL_ACCURACY.md`.", "",
             "## By contributor", "", "| contributor | files | events | kept | verified | reported cost | cost per kept fact |", "|---|---:|---:|---:|---:|---:|---:|"]
    for k, a in sorted(by_agent.items()):
        per = money(a["cost"] / a["kept"]) if a["costed"] and a["kept"] else "-"
        lines.append(f"| {k} | {a['files']} | {a['events']} | {a['kept']} | {a['verified']} | {money(a['cost']) if a['costed'] else '-'} | {per} |")
    lines += ["", "## Every run", "", "| date | file | contributor | model id | events | kept | verified | provenance lines | tokens | cost |", "|---|---|---|---|---:|---:|---:|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (r["date"], r["file"])):
        lines.append(f"| {r['date']} | `{r['file']}`{' (rejected)' if r.get('rejected') else ''} | {r['agent']} | {r['models']} | {r['events']} | {r['kept']} | {r['verified']} | {r['provenance']} | {r['tokens'] if r['tokens'] is not None else '-'} | {money(r['cost'])} |")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(rows)} runs")
    for k, a in sorted(by_agent.items()): print(f"  {k:8} {a['files']:3} files {a['events']:5} events {a['kept']:5} kept {a['verified']:3} verified  cost {money(a['cost']) if a['costed'] else 'not reported'}")


if __name__ == "__main__":
    sys.exit(main())
