#!/usr/bin/env python3
"""Turn schema/seed/albums.seed.json (the ledger ALBUMS.md transcription) into wings/albums-data.js.

The Curator's Study reads `window.TITAN_ALBUMS` from that file, so the album UI shows ledger data
instead of the numbers hand-typed into app.js (ALBUM_METADATA). Nothing is guessed here: fields are
copied as-is; only the keys the UI needs are kept.

Usage:  python3 tools/albums/seed_to_js.py [schema/seed/albums.seed.json] [wings/albums-data.js]
"""
import json
import sys

KEEP = ("id", "family", "title", "slots_total", "slots_approx", "filled_count", "evidence",
        "filled", "holes", "note", "unaccounted", "problems_vs_app")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "schema/seed/albums.seed.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "wings/albums-data.js"
    with open(src, encoding="utf-8") as f:
        seed = json.load(f)
    vols = [{k: v.get(k) for k in KEEP} for v in seed["volumes"]]
    payload = {
        "source": seed.get("source"),
        "built_by": "tools/albums/seed_to_js.py from " + src,
        "totals": seed.get("totals"),
        "volumes": vols,
    }
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    with open(out, "w", encoding="utf-8") as f:
        f.write("/* GENERATED by tools/albums/seed_to_js.py from schema/seed/albums.seed.json. Do not edit by hand.\n")
        f.write("   Ledger album data (Grok ALBUMS.md). evidence: enumerated = every slot accounted for;\n")
        f.write("   partial = some slots named; count-only = only the fill count is known. */\n")
        f.write("window.TITAN_ALBUMS = " + body + ";\n")
    print(f"wrote {out}: {len(vols)} volumes")


if __name__ == "__main__":
    main()
